title: A hello world workflow
tagline: A hello world workflow
description: A hello world workflow
tags:
  - GitHub Actions
  - Workflows
  - Hello World
template:
    name: hello-world-actions
    repo: hello-world-actions-template
before:
# protect the master branch
- type: updateBranchProtection

# open issue 1 (welcome)
- type: createIssue
  title: Welcome
  body: welcome.md

# Repo artifacts:
# Issue 1: Welcome
# PR 2: (created by learner) houses the addition of the Dockerfile, entrypoint script, and workflow
# Issue 3: Congratulations

steps:

# 1 - Add a Dockerfile
- title: Add a Dockerfile
  description: Add a Dockerfile
  event: pull_request
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:action-a/Dockerfile
    else:
      type: respond
      with: e-no-docker.md
  - type: respond
    with: docker-success.md
  - type: closeIssue
    issue: Welcome

# 2 - Add an entrypoint script
- title: Add an entrypoint script
  description: Add an entrypoint script
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/2'
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:action-a/entrypoint.sh
    else:
      type: respond
      with: e-no-entrypoint.md
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: mode:100755
    else:
      type: respond
      with: e-make-exec.md
      data:
        repo: '%payload.repository%'
        branch: '%payload.pull_request.head.ref%'
  - type: respond
    with: entrypoint-success.md

# 3 - Add a `workflow` block to your workflow file
- title: Add a `workflow` block to your workflow file
  description: Add a `workflow` block to your workflow file
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/2'
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: workflow-block-success.md

# 4 - Add an action block to your workflow file
- title: Add a `action` block to your workflow file
  description: Add a `action` block to your workflow file
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/2'
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: trigger.md


# 5 - Trigger the workflow
- title: Trigger the workflow
  description: Trigger the workflow
  event: check_suite.completed
  link: '{{ repoUrl }}/pull/2'
  actions:
  - type: gate
    left: '%payload.check_suite.app.name%'
    operator: ===
    right: GitHub Actions
  - type: gate
    left: '%payload.check_suite.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_suite.pull_requests.0.number%'
      with: e-no-run.md
      data:
        repo: '%payload.repository.html_url%'
  - type: createReview
    pullRequest: '%payload.check_suite.pull_requests.0.number%'
    body: workflow-success.md
    event: APPROVE
    data:
      repo: '%payload.repository.html_url%'

# 6 - Incorporate the action
- title: Incorporate the workflow
  description: Incorporate the workflow
  event: pull_request.closed
  link: '{{ repoUrl }}/pull/2'
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.action%'
      operator: ===
      right: closed
    - left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Congratulations
    body: workflow-finished.md
    data:
      repo: '%payload.repository.html_url%'
    action_id: congratsIssue
  - type: respond
    with: go-to-final.md
    data:
      url: '%actions.congratsIssue.data.html_url%'
