title: A hello world workflow
tagline: A hello world workflow
description: A hello world workflow
tags:
  - GitHub Actions
  - Workflows
  - Hello World
template:
    name: hello-world-actions
    repo: hello-world-actions-template
before:
# protect the master branch
- type: updateBranchProtection

# open issue 1 (welcome)
- type: createIssue
  title: Welcome
  body: welcome.md

# Repo artifacts:

steps:

# 1 - Add a Dockerfile
- title: Add a Dockerfile
  description: Add a Dockerfile
  event: pull_request
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:action-a/Dockerfile
    else:
      type: respond
      with: e-no-docker.md
  - type: respond
    with: docker-success.md

# 2 - Add an entrypoint script
- title: Add an entrypoint script
  description: Add an entrypoint script
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:action-a/entrypoint.sh
    else:
      type: respond
      with: e-no-entrypoint.md
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: mode:100755
    else:
      type: respond
      with: e-make-exec.md
      data:
        repo: '%payload.repository%'
        branch: '%payload.pull_request.head.ref%'
  - type: respond
    with: entrypoint-success.md

# 3 - Create your workflow
- title: Create your workflow
  description: Create your workflow
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: trigger.md

# 4 - Trigger the workflow
- title: Trigger the workflow
  description: Trigger the workflow
  event: check_run
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_run.app.name%'
      operator: ===
      right: GitHub Actions
    - left: '%payload.check_run.status%'
      operator: ===
      right: completed
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_run.pull_requests.0.number%'
      with: e-no-run.md
      data:
        url: '%payload.check_run.html_url%'
        repo: '%payload.repository.html_url%'
  - type: createReview
    pullRequest: '%payload.check_run.pull_requests.0.number%'
    body: workflow-success.md
    event: APPROVE
    data:
      url: '%payload.check_run.html_url%'

# 5 - Incorporate the action
- title: Incorporate the workflow
  description: Incorporate the workflow
  event: pull_request.closed
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.action%'
      operator: ===
      right: closed
    - left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Congratulations
    body: workflow-finished.md
    data:
      repo: '%payload.repository.html_url%'
    action_id: congratsIssue
  - type: respond
    with: go-to-final.md
    data:
      url: '%actions.congratsIssue.data.html_url%'
