title: A hello world workflow
tagline: A hello world workflow
description: A hello world workflow
tags:
  - GitHub Actions
  - Hello World
template:
    name: hello-world-actions
    repo: false
before:
# open issue 1 (welcome)
- type: createIssue
  title: Welcome
  body: welcome.md

# Repo artifacts:

steps:

# 1 - Add a Dockerfile
- title: Add a Dockerfile
  description: Add a Dockerfile
  event: pull_request.opened
  actions:
  # TODO: check Dockerfile exists
  - type: respond
    with: docker-success.md

# 2 - Add an entrypoint script
- title: Add an entrypoint script
  description: Add an entrypoint script
  event: pull_request.synchronize
  actions:
  # TODO: check if script file exists
  # TODO: check if script file is executable
  - type: respond
    with: entrypoint-success.md

# 3 - Create your workflow
- title: Create your workflow
  description: Create your workflow
  event: pull_request.synchronize
  actions:
  - type: respond
    with: trigger.md
  
# 4 - Trigger the workflow
- title: Trigger the workflow
  description: Trigger the workflow
  event: pull_request.closed
  actions:
  # TODO: check that it is the closed PR and merged
  - type: respond
    with: workflow-triggered.md

# 5 - Run the action
- title: Run the action
  description: Run the action
  event: check_suite
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_suite.app.name%'
      operator: ===
      right: GitHub Actions
    - left: '%payload.check_suite.status%'
      operator: ===
      right: completed
      else:
      - type: createIssue
        title: The workflow didn't run
        body: e-no-run.md
  - type: createIssue
    title: Congratulations
    body: workflow-success.md