title: A hello world workflow
tagline: A hello world workflow
description: A hello world workflow
tags:
  - GitHub Actions
  - Workflows
  - Hello World
template:
    name: hello-world-actions
    repo: hello-world-actions-template
before:
# protect the master branch
- type: updateBranchProtection

# open issue 1 (welcome)
- type: createIssue
  title: Welcome
  body: welcome.md

# Repo artifacts:

steps:

# 1 - Add a Dockerfile
- title: Add a Dockerfile
  description: Add a Dockerfile
  event: pull_request.opened
  actions:
  - type: getFileContents
    filename: action-a/Dockerfile
    required: false
    action_id: theDockerfile
  - type: gate
    left: '%actions.theDockerfile%'
    else: 
    - type: respond
      with: e-no-docker.md
  - type: respond
    with: docker-success.md

# 2 - Add an entrypoint script
- title: Add an entrypoint script
  description: Add an entrypoint script
  event: pull_request.synchronize
  actions:
  # TODO: check if script file is executable
  - type: getFileContents
    filename: action-a/entrypoint.sh
    required: false
    action_id: theScript
  - type: gate
    left: '%actions.theScript%'
    else: 
    - type: respond
      with: e-no-entrypoint.md
  - type: respond
    with: entrypoint-success.md

# 3 - Create your workflow
- title: Create your workflow
  description: Create your workflow
  event: pull_request.synchronize
  actions:
  - type: respond
    with: trigger.md

# 4 - Trigger the workflow
- title: Trigger the workflow
  description: Trigger the workflow
  event: check_run
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_run.app.name%'
      operator: ===
      right: GitHub Actions
    - left: '%payload.check_run.status%'
      operator: ===
      right: completed
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_run.pull_requests.0.number%'
      with: e-no-run.md
      data:
        url: '%payload.check_run.html_url%'
  - type: respond
    issue: '%payload.check_run.pull_requests.0.number%'
    with: workflow-success.md
    data:
      url: '%payload.check_run.html_url%'

# 5 - Incorporate the action
- title: Incorporate the workflow
  description: Incorporate the workflow
  event: pull_request.closed
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.action%'
      operator: ===
      right: closed
    - left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Congratulations
    body: workflow-finished.md
    data:
      repo: '%payload.repository.html_url%'
    action_id: congratsIssue
  - type: respond
    with: go-to-final.md
    data:
      url: '%actions.congratsIssue.data.html_url%'
